services:
  db:
    image: postgres:16-alpine
    container_name: employee_db_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: employee_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    # AJOUT : Définition de la santé du conteneur
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d employee_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/employee_db
      - HF_MODEL_REPO=${HF_MODEL_REPO:-}
    volumes:
      - ./data_merge.csv:/app/data_merge.csv
      - ./models:/app/models
    # L'application attend maintenant que le healthcheck de 'db' passe
    depends_on:
      db:
        condition: service_healthy

  seed:
    build: .
    container_name: seed_service
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/employee_db
    volumes:
      - ./data_merge.csv:/app/data_merge.csv
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy
    command: /bin/uv run ./app/seed.py --csv-file data_merge.csv --update --database-url postgresql://postgres:mysecretpassword@db:5432/employee_db
    restart: "no"

volumes:
  postgres_data: